apache-php559:
    build: ./apache
    ports:
        - "80:80"
    volumes:
        - ./..:/var/www
        - ./apache/conf/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - ./apache/sites:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - "db:db"

nginx:
    image: nginx
    ports:
        - "8080:8080"
    links:
        - "php7:php7"
    volumes:
        - ./..:/var/www
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"

php7:
    image: tamtamp/php7
    ports:
        - "9000:9000"
    volumes:
        - ./..:/var/www
    links:
        - db:db

db:
    image: mysql
    ports:
        - "3306:3306"
    volumes:
        - /var/lib/boot2docker/mysql:/var/lib/mysql
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
