api:
    build: ./api
    volumes:
        - ./../apittp:/var/www/apittp
    tty: true

apache-php559:
    build: ./apache
    restart: always
    ports:
        - "8080:80"
    volumes_from:
        - api
    volumes:
        - ./apache/conf/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - ./apache/sites:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - "db:db"

nginx:
    build: ./nginx
    restart: always
    ports:
        - "80:80"
    links:
        - "php7:php7"
    volumes_from:
        - api
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

php7:
    image: tamtamp/php7
    restart: always
    ports:
        - "9000:9000"
    volumes_from:
        - api
    links:
        - db:db

db:
    image: mysql
    restart: always
    ports:
        - "3306:3306"
    volumes:
        - /var/lib/boot2docker/mysql:/var/lib/mysql
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
